export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const INIT_BUILDING_INGREDIENTS = 'INIT_BUILDING_INGREDIENTS';
export const SET_BUILDING_INGREDIENTS = 'SET_BUILDING_INGREDIENTS';
export const INIT_ADDED_INGREDIENTS = 'INIT_ADDED_INGREDIENTS';
export const SET_ADDED_INGREDIENTS = 'SET_ADDED_INGREDIENTS';

export const ADD_INGREDIENT = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENT_BY_TYPE = 'REMOVE_INGREDIENT_BY_TYPE';
export const REMOVE_INGREDIENT_BY_INDEX = 'REMOVE_INGREDIENT_BY_INDEX';
export const CHANGE_INGREDIENT_POSITION = 'CHANGE_INGREDIENT_POSITION';

//TODO: IMPLEMENT THOSE ACTIONS
export const FETCH_BUILDING_INGREDIENTS_FAILED = 'FETCH_BUILDING_INGREDIENTS_FAILED';
export const FETCH_INIT_INGREDIENTS_ORDER_FAILED  = 'FETCH_INIT_INGREDIENTS_ORDER_FAILED';

export const RESET_IS_PURCHASED = 'RESET_IS_PURCHASED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const INIT_AUTH_STATE = 'INIT_AUTH_STATE';
export const SET_AUTH_STATE = 'SET_AUTH_STATE';


//OLD
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AFTER_AUTH_REDIRECT_PATH = 'SET_AFTER_AUTH_REDIRECT_PATH';