export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const INIT_BUILDING_INGREDIENTS = 'INIT_BUILDING_INGREDIENTS';
export const SET_BUILDING_INGREDIENTS = 'SET_BUILDING_INGREDIENTS';
export const INIT_ADDED_INGREDIENTS = 'INIT_ADDED_INGREDIENTS';
export const SET_ADDED_INGREDIENTS = 'SET_ADDED_INGREDIENTS';

export const ADD_INGREDIENT = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENT_BY_TYPE = 'REMOVE_INGREDIENT_BY_TYPE';
export const REMOVE_INGREDIENT_BY_INDEX = 'REMOVE_INGREDIENT_BY_INDEX';
export const CHANGE_INGREDIENT_POSITION = 'CHANGE_INGREDIENT_POSITION';

export const ORDER_BURGER = 'ORDER_BURGER';
export const SET_IS_BURGER_ORDERED = 'SET_IS_BURGER_ORDERED';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const INIT_AUTH_STATE = 'INIT_AUTH_STATE';
export const SET_AUTH_STATE = 'SET_AUTH_STATE';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const SET_AFTER_AUTH_REDIRECT_PATH = 'SET_AFTER_AUTH_REDIRECT_PATH';